CREATE TABLE {{TABLE}} (
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT '0000-00-00 00:00:00',
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT DEFAULT '',
    PRIMARY KEY  (id)
) {{CHARSET}};
