CREATE TABLE {{TABLE}} (
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    campaign_id INTEGER UNSIGNED,
    ad_id INTEGER UNSIGNED NOT NULL,
    start_date DATETIME DEFAULT '0000-00-00 00:00:00',
    end_date DATETIME DEFAULT '9999-12-31 23:59:59',
    PRIMARY KEY  (id)
) {{CHARSET}};
